### ISSUE TITLE
Integrate econplayground.js into this repository

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/econplayground#2089]
I think it's about time to clean things up here - this project still uses a bootleg setup I configured many years ago to split the JS code from the Django code. We've seen with Mediathread and now mathplayground that it's simple to have both in a single repository. So I'd like to integrate this repo in here: https://github.com/ccnmtl/econplayground.js

**Comment by Evan-CTL** [comment]
Pull Request made: https://github.com/ccnmtl/econplayground/pull/2094

**Comment by nikolas** [comment]
We can close this once #2117 is merged
