### ISSUE TITLE
Tags in Question Model

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/econplayground#2273]
Add a tags property to the `Question` model:
- A list of strings which correspond to the titles of the question banks that reference the Question.
- Displayed in the Question List. Might help to convert the list into a table.
- This request might be followed up with a tags search function, but for now going into the detail view of a question bank will display the referenced questions.

**Comment by nikolas** [comment]
Closing this for now as we don't have question banks implemented yet.
