### ISSUE TITLE
No hover effect on 'About' and 'Contact' buttons.

### ISSUE THREAD

**Issue by SumitVerma-coder** [ccnmtl/econplayground#2769]
The hover effect is absent on 'About' and 'Contact' buttons.
![image](https://github.com/ccnmtl/econplayground/assets/112965155/5112c9c8-2b28-457b-a275-f97e61bf8019)
**_PLEASE ASSIGN ME THIS ISSUE UNDER HACTOBERFEST TAG._**

**Comment by nikolas** [comment]
Closing as this is not really an issue.
