### ISSUE TITLE
Explore using KaTeX or MathJax directly

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/econplayground#3308]
We're having some mathjax formatting problems that may be related to our use of the better-mathjax-react library. There are so many different latex/mathjax libraries aimed to tie these projects to React, and they come and go quickly and rarely maintained for very long. I'm thinking we might have better luck just coming up with our own React component and using one of these libraries in a more direct manner, without relying on random, non-standard react libraries.

* https://katex.org/
* https://www.mathjax.org/

**Comment by Evan-CTL** [comment]
Fair point. It could help us establish a standard across our platforms.
